modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
issueTrackerURL="https://github.com/caltinor" #optional
displayURL="https://github.com/caltinor" #optional
#logoFile="" #optional
credits="Thanks to the MMD community." #optional
authors="Caltinor" #optional
license="ARR License"

[[mods]] #mandatory
modId="dicemcsjm" #mandatory
version="1.16.5-1.0" #mandatory
displayName="Simple Jail Mod" #mandatory
#updateJSONURL=""
description='''
A simple server-side jailing mod
'''

[[dependencies.dicemcsjm]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32.0.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dicemcsjm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"